# Generated by Django 5.1.7 on 2025-06-13 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_doctor_delete_doctor_email_appointment_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
    ]
