# Generated by Django 5.1.7 on 2025-06-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_appointment_email_remove_appointment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
